# Generated by Django 4.2.16 on 2025-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Versao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=10, unique=True)),
                ("data_lancamento", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("funcionalidade", "Funcionalidade"),
                            ("implementacao", "Implementação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
    ]
