# Generated by Django 5.2.4 on 2025-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_itenssolicitacao_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenstransferencia',
            name='nome',
            field=models.CharField(max_length=160),
        ),
    ]
