# Generated by Django 4.2.15 on 2024-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_itenssolicitacao_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
